# Generated by Django 3.2.9 on 2022-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edcName', models.CharField(max_length=30)),
                ('edcBoss', models.CharField(max_length=30)),
                ('edcCreateDate', models.DateField()),
            ],
        ),
    ]
