# Generated by Django 3.2.9 on 2022-01-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EdCenter',
            new_name='EducationalCenter',
        ),
    ]
