# Generated by Django 3.2.9 on 2022-01-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0002_rename_edcenter_educationalcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=30)),
                ('howManyStudents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('studentSubjects', models.CharField(max_length=255)),
                ('registrationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30)),
                ('subjectTeacher', models.CharField(max_length=30)),
                ('subjectDay1', models.CharField(choices=[('Понедельник', 'Пн'), ('Вторник', 'Вт'), ('Среда', 'Ср')], max_length=11)),
                ('subjectDay2', models.CharField(choices=[('Четверг', 'Чт'), ('Пятница', 'Пт'), ('Суббота', 'Сб')], max_length=11)),
                ('howManyGroups', models.IntegerField()),
            ],
        ),
    ]
