# Generated by Django 3.2.9 on 2022-01-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0003_groups_student_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
