# Generated by Django 3.2.9 on 2022-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
