# Generated by Django 3.2.9 on 2022-01-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalCenter',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
