# Generated by Django 3.2.9 on 2022-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0009_profileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLoginAndPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
