# Generated by Django 3.2.9 on 2022-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0010_profileloginandpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_many', models.IntegerField()),
            ],
        ),
    ]
