# Generated by Django 3.2.9 on 2022-03-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dar', '0011_jaimodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
