# Generated by Django 3.2.9 on 2022-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdFirstName', models.CharField(max_length=255)),
                ('stdSurname', models.CharField(max_length=255)),
                ('stdDayOfBirth', models.DateField()),
                ('stdIIN', models.CharField(max_length=12)),
                ('stdPrSubject1', models.CharField(max_length=255)),
                ('stdPrSubject2', models.CharField(max_length=255)),
            ],
        ),
    ]
